### ISSUE TITLE
Une favicon pour le site

### ISSUE THREAD

**Issue by MicroJoe** [haum/website#15]
Et pourquoi pas ? J’ai vu dans tous mes onglets ouverts que seul celui du site du Haum n’en possédait pas. Quelques prototypes que j’ai réalisés sont disponibles sur `ftp://ftp.microjoe.org/haum/favicon/` mais ils sont bien sûr modifiables.

**Comment by fredblain** [comment]
Je pense que ça ne peut pas faire de mal.
Ta proposition ou rependre le logo de Laurent (logo des mugs) me plaisent bien.

**Comment by MicroJoe** [comment]
Je viens de vérifier et je n'ai rien qui s'affiche sur le site. J'ai regardé dans le code de la page d'accueil, il y a un genre de lien vers une icône (mais j'ai jamais vu de favicon déclarée comme ça) qui pointe vers une 404 :

    The requested URL /theme/static/images/favicon.ico was not found on this server.

On peut générer des favicons pour les systèmes à la pomme avec des déclarations spéciales même si c'est pas urgent ; faudrait vraiment que je regarde pour contribuer au code du site moi.
