### ISSUE TITLE
Manque le fichier calendar.js dans le dépôt

### ISSUE THREAD

**Issue by MicroJoe** [haum/website#16]
Je viens de cloner le dépôt. Un `make html` me dit que le script n'arrive pas à trouver le fichier `content/calendar/calendar.js` qui doit je pense servir à la génération du calendrier côté client.

Le fichier apparaît en effet dans le `.gitignore` du dépôt, quelqu'un l'a peut-être rajouté dedans par mégarde.

**Comment by fredblain** [comment]
On 02.07.15 at  8:16, Romain Porte wrote:
> Je viens de cloner le dépôt. Un `make html` me dit que le script
> n'arrive pas à trouver le fichier `content/calendar/calendar.js` qui
> doit je pense servir à la génération du calendrier côté client.
> Le fichier apparaît en effet dans le `.gitignore` du dépôt, quelqu'un
> l'a peut-être rajouté dedans par mégarde.
Non, c'est sciemment voulu:
https://github.com/haum/website/commit/bbf49ff22e896233dc8eb1fdf180142b96d0167a

Par contre en effet, ca ne compile pas a partir d'un nouveau repo... A
voir pourquoi mais en attendant, creer un calendar.js vierge devrait
resoudre ton pb et te permettre de compiler.

a plus tard,
Fred.

**Comment by MicroJoe** [comment]
Je viens de trouver pourquoi, c'est parce-que le dossier `calendar/` n'existe pas (car il ne contient aucun fichier et git ne peut donc pas indexer seulement un dossier).

Je vais tenter un fix en créant un fichier bidon qui permettra de garder le dossier présent et permettre un fonctionnement dès le clonage.

**Comment by MicroJoe** [comment]
Voir ec1d52dd7460f302a4c8764c0a5a71bff29209d4.

**Comment by Matael** [comment]
Plutôt qu'un fichier bidon, il est préférable d'utiliser des noms standards, typiquement, .gitkeep

**Comment by MicroJoe** [comment]
Je vais m'empresser de corriger ça.

**Comment by Matael** [comment]
Merci :)

**Comment by MicroJoe** [comment]
Pas de soucis. :)
