### ISSUE TITLE
Séparer le planet des articles

### ISSUE THREAD

**Issue by MicroJoe** [haum/website#19]
Si on met en avant les articles (cf #18), je ne pense pas que les articles du planet méritent le même sort car ils concernent moins l'association à mon avis.

On peut le garder mais simplement le mettre à part, ce qui permettera de faire la distiction association/contenu perso. des membres qui n'ont pas tellement rapport avec celle-ci.

**Comment by fredblain** [comment]
Les articles du planet ne meritent pas le meme sort ? Peux-tu donner un exemple de publication sur le planet qui n'a aucun rapport avec l'asso stp ?

Je ne suis pas d'avis de toujours tout separer, tout le temps, ca n'incite pas a publier. Si par la suite, tel ou tel contenu se voit devalorise pour une raison ou pour une autre, qu'il vaut moins qu'un compte-rendu de seance. Autant dire tout de suite que seul(s les presents aux seances sont invites a ecrire quelque chose si le reste est "moins meritant" et reclasse dans une sous-partie du site que personne ne metrra en valeur. Qu'on supprime le planet dans ce cas.

**Comment by Matael** [comment]
Pourquoi ne pas classé les comptes rendu de séances à part (qui ont valeur de compte rendu, soit aucune sauf pour ceux qui veulent savoir ce qui se passe) et garder grouper planet et le reste d'autre part pour leur valeur et leur discours plus profond d'autre part ?

L'avantage : on peut mettre en avant les articles (et produire par exemple des condensés sur tel ou tel projet ou des explications sur telle ou telle technique) tout en gardant un log chronologique de ce qui se passe (et qui, à mon sens, a nettement moins de "valeur").

**Comment by jblb** [comment]
j'étais un peu de l'avis de @MicroJoe tout en ayant la réflexion de @fredblain c'est pourquoi j'aime bien la proposition de @Matael qui ménage la chèvre et le choux. Vive lui !

**Comment by MicroJoe** [comment]
J'aime bien également la proposition de @Matael. Voir #21 du coup.
