### ISSUE TITLE
Centrer les images du module Flickr

### ISSUE THREAD

**Issue by MicroJoe** [haum/website#20]
Il me semle qu'à un moment les photos provenant du Flickr étaient centrées mais cela ne semble plus être le cas actuellement (voir http://haum.org/seance_20150721.html).

Je sais qu'il est possible de mettre deux photos côte à côte mais ça n'est pas incompatible avec le centrage, qu'il y ait une photo ou plusieurs collés.

**Comment by jblb** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Sur la page http://haum.org/test_flickr.html elles sont centrées regarde le code qui y est associer. De mémoire j'avais eu du mal à mettre ça en place, de la à ce qu'il reste un bug y a qu'un pas

Le 17 août 2015 01:55:50 CEST, Romain Porte <notifications@github.com> a écrit :
>Il me semle qu'à un moment les photos provenant du Flickr étaient
>centrées mais cela ne semble plus être le cas actuellement (voir
>http://haum.org/seance_20150721.html).
>
>Je sais qu'il est possible de mettre deux photos côte à côte mais ça
>n'est pas incompatible avec le centrage, qu'il y ait une photo ou
>plusieurs collés.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/haum/website/issues/20

- --
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQFABAEBCgAqBQJV0YyuIxxKZXJvbWUgQi4gKEpiTGIpIDxqZXJvbWVAamJsYi5u
ZXQ+AAoJELfBan+yggskvZsH/jglEajhepok1KJG1rai4guvWCfyTcoGQBTKJcrR
3dbL2fRauQNXh/Nsq3Oy5Obp1TkBEHX+5Tq9JNOWUODhKgpTqcUxj9j6MWIhyT00
DiolHrUON6GPT79ilvJ1+ZEzqRXP0dFe27cE5DnNXoNncZwDcPC2FJMVuKu7A3sO
rtGuyCEno5hJ9kr4KSnzdGVrNCxls+e6WZJb+1frQCBXy+XtcyA75cYN1uLgHKow
GUXGDqG6Alx2eRsvIeLU9Q7HuJITaXbP/i/3ze7hteRGWiO6QE0NY1ExFWFyCbKW
LXplUUFMiDZ/iBiWMiUS+HMZ0jI0p1Dk65Q25f5OyY0aJUA=
=6g8K
-----END PGP SIGNATURE-----

**Comment by sebvallee** [comment]
Est ce que le centrage n'est pas quelque chose que reStructuredText/Pelican doit faire, et qu'on doit donc indiquer dans la mise en page de l'article?

Comme dans le lien fourni par @jblb, il semble qu'une simple ligne, préalable à l'appel de l'image, centre celle ci sur la page.

**Comment by MicroJoe** [comment]
En effet :

    .. container:: aligncenter
