### ISSUE TITLE
Réduire le nombre d'éléments dans le flux RSS

### ISSUE THREAD

**Issue by MicroJoe** [haum/website#26]
En s'abonnant au flux RSS du site celui-ci contient 58 entrées.

Une limite communément admise pour les flux RSS est de 10 éléments. Il faudrait appliquer cette limite au flux généré par Pelican pour ne pas spammer les clients RSS et réduire aussi la bande passante utilisée à chaque transmission du fichier XML.

**Comment by JackDesBwa** [comment]
Sur ma station de développement, le flux all.atom.xml n'est pas généré. Y aurait-t-il une différence de configuration qui n'est pas sur le dépôt (?!) ou peut-être une  procédure différente qui mènerait à le générer.

Je ne peux donc pas tester, mais il semble exister une variable FEED_MAX_ITEMS à déclarer dans le fichier de configuration pour limiter le nombre d'entrées dans les flux. (source http://docs.getpelican.com/en/3.1.1/settings.html)

**Comment by Matael** [comment]
@Jackdesbwa tu utilises bien make publish pour générer ? Il y a un bout de la configuration dans publishconf.py qui génère les flux. Je vais essayer de me pencher sur cette issue tout à l'heure

**Comment by JackDesBwa** [comment]
En effet, je n'avais pas noté qu'il y avait une configuration différente pour la publication.
J'utilisais pour ma part _make devserver_ qui ne prend pas cette surcharge de configuration.

La variable semble fonctionner.
