### ISSUE TITLE
Un planet chronologique

### ISSUE THREAD

**Issue by MicroJoe** [haum/website#28]
Le planet ne trie pas les articles par date, ce qui fait que j'ai l'impression que le dernier qui a ajouté son blog au planet (moi actuellement) voit ses articles apparaître avant tous les autres.

Il faut donc améliorer le planet pour que celui-ci prenne en compte la date de publication pour effectuer un tri.

**Comment by JackDesBwa** [comment]
Sur le planet, il y a 4 contributeurs ; dont 3 avec les liens cassés.
J'ai corrigé le fetch pour feedoo (du coup on aura de nouveau 1 article supplémentaire quand ce sera propagé)

Pour trier par date, il faudrait que toutes les sources aient une date, hors
- ce n'est pas dans la structure reçue (mais ça peut se changer vul le peu de blogs liés)
- la page de feedoo n'indique pas de date par exemple

Se pose alors la question... est-il pertinent de garder un planet dans ces conditions ?

**Comment by MicroJoe** [comment]
J'ai rajouté le miens par curiosité de voir comment ça fonctionnait mais vu le soin pris pour le garder en vie je ne serai pas contre le retirer. Ou du moins le masquer pour ne pas avoir que mes derniers articles dessus, ce qui ne fait pas très communautaire.
